version: "3.3"

services:

  traefik:
    image: "traefik:v2.0.0-rc3"
    container_name: "traefik"
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      # Traefik will listen to incoming request on the port 443 (https)
      - "--entrypoints.websecure.address=:443"
      # Enable a http challenge named "myhttpchallenge"
      - "--certificatesresolvers.myhttpchallenge.acme.httpchallenge=true"
      # Tell it to use our predefined entrypoint named "web"
      - "--certificatesresolvers.myhttpchallenge.acme.httpchallenge.entrypoint=web"
      # - "--certificatesresolvers.myhttpchallenge.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      # - "--certificatesresolvers.myhttpchallenge.acme.caserver=https://acme-v02.api.letsencrypt.org/directory"      
      # The email to provide to let's encrypt
      - "--certificatesresolvers.myhttpchallenge.acme.email=tuanvu0695@gmail.com"
      - "--certificatesresolvers.myhttpchallenge.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      # - "8080:8080"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
  
  tuans_blogs_rails:
    build: .
    depends_on:
      - sqlite3
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`tuanblog.funniq.com`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.tls.certresolver=myhttpchallenge"
    # ports:
      # - "8085:3000"
  
  sqlite3:
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true    
    volumes:
      - /home/tuan/db/sqlite3:/root/db/

  
  # whoami:
  #   image: "containous/whoami"
  #   container_name: "simple-service"
  #   labels:
  #     - "traefik.enable=false"
  #     - "traefik.http.routers.whoami.rule=Host(`tuanblog.funniq.com`)"
  #     - "traefik.http.routers.whoami.entrypoints=websecure"
  #     - "traefik.http.routers.whoami.tls.certresolver=myhttpchallenge"